spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videocourse
    username: postgres
    password: admin
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 9090